### ISSUE TITLE
Automate the new YANG module addition, for the IETF, Standard Development Organizations, and vendors

### ISSUE THREAD

**Issue by evyncke** [YangCatalog/sdo_analysis#1]
Per SoW "Automate the new YANG module addition, for the IETF, Standard
Development Organizations, and vendors"

**Comment by miroslavKovacPantheon** [comment]
This should be done as far as I know. Please let me know if this needs some more attention.

Thank  you

**Comment by evyncke** [comment]
AFAIK it is not done automatically, still no IOS-XR 6.5.* for example.

`runYANGgenericstats-weekly.sh` still have hard-coded path and version names
