### ISSUE TITLE
YANG catalog impact analysis does not contain the latest draft versions

### ISSUE THREAD

**Issue by bclaise** [YangCatalog/sdo_analysis#103]
Hi,

https://yangcatalog.org/yang-search/impact_analysis/ietf-x509-cert-to-name@2014-12-10
I clicked on the red circles to find out the related drafts.
In this case: etf-https-notif.
It points to https://datatracker.ietf.org/doc/draft-ietf-netconf-https-notif/06
So the draft version 6, while version 9 exists: https://datatracker.ietf.org/doc/draft-ietf-netconf-https-notif/09/

Please update the draft versions in the impact analysis (and find out the reason why it's not done automatically).

Regards, Benoit

**Comment by SlavomirMazurPantheon** [comment]
Hello,

this should definitely be done automatically. After using rsync to get all the drafts, modules are parsed out of these drafts and stored to the YANG Catalog.
It looks like ietf-subscribed-notif-receivers@2021-10-24 from draft https://datatracker.ietf.org/doc/draft-ietf-netconf-https-notif/09/ is missing. I will check why this happened.

Regards,
Slavomir Mazur

**Comment by SlavomirMazurPantheon** [comment]
Hello,

I checked this problem and I figured out that this doesn't seem to be a problem in impact-analysis. This is list of drafts with corresponding modules which were extracted from them:

[draft-ietf-netconf-https-notif-06.txt](https://datatracker.ietf.org/doc/draft-ietf-netconf-https-notif/06/)
```
ietf-sub-notif-recv-list@2020-11-16.yang
ietf-https-notif@2020-11-16.yang
example-custom-module.yang
```
[draft-ietf-netconf-https-notif-07.txt](https://datatracker.ietf.org/doc/draft-ietf-netconf-https-notif/07/)
```
ietf-subscribed-notif-receivers@2021-02-02.yang
ietf-https-notif-transport@2021-02-02.yang
example-custom-module.yang
```

[draft-ietf-netconf-https-notif-08.txt](https://datatracker.ietf.org/doc/draft-ietf-netconf-https-notif/08/)
```
ietf-subscribed-notif-receivers@2021-02-22.yang
ietf-https-notif-transport@2021-02-22.yang
example-custom-module.yang
```

[draft-ietf-netconf-https-notif-09.txt](https://datatracker.ietf.org/doc/draft-ietf-netconf-https-notif/09/)
```
ietf-subscribed-notif-receivers@2021-10-24.yang
ietf-https-notif-transport@2021-10-24.yang
example-custom-module.yang
```

As we can see that mentioned **ietf-https-notif** module was extracted from draft version 6, but from version 7 it was renamed to **ietf-https-notif-transport**.
This is the reason, why it points to https://datatracker.ietf.org/doc/draft-ietf-netconf-https-notif/06 and not https://datatracker.ietf.org/doc/draft-ietf-netconf-https-notif/09

Regards,
Slavomir Mazur

**Comment by bclaise** [comment]
Nice investigation. So no bug on the yc.o, which is good.
I can't find of an easy and obvious fix, in the yangcatalog metadata, or in the GUI.
Please close this one.
