### ISSUE TITLE
BBFYANGPageCompilation.html (etc.) error message formatting has missing newlines (and other comments)

### ISSUE THREAD

**Issue by wlupton** [YangCatalog/sdo_analysis#119]
I'm not sure if this is the right place to report this... please let me know if not.

I noticed that [BBFYANGPageCompilation.html](https://yangcatalog.org/private-page/BBFYANGPageCompilation.html) is running multiple yangdump-pro (and maybe other tool?) error messages on to a single line. For example this:
```
Warning: revision with same date on line 123 iana-if-type@2021-06-21.yang:128.3: warning(1054): Revision date has already been used Error: leaf node 'interval-number' on line 336 not valid type in key, for list 'history' (NONE) bbf-fast-channel-performance-body.yang:331.11: error(252): type not allowed in index Error: leaf node 'interval-number' on line 387 not valid type in key, for list 'history' (NONE) bbf-fast-channel-performance-body.yang:382.11: error(252): type not allowed in index *** 2 Errors, 0 Warnings
```

...might be better formatted as:
```
Warning: revision with same date on line 123 iana-if-type@2021-06-21.yang:128.3: warning(1054): Revision date has already been used
Error: leaf node 'interval-number' on line 336 not valid type in key, for list 'history' (NONE) bbf-fast-channel-performance-body.yang:331.11: error(252): type not allowed in index
Error: leaf node 'interval-number' on line 387 not valid type in key, for list 'history' (NONE) bbf-fast-channel-performance-body.yang:382.11: error(252): type not allowed in index
*** 2 Errors, 0 Warnings
```

Also (these might be due to the tool, but perhaps are due to its options or how the output is captured):
* The messages are largely duplicated, e.g., both `Warning: revision with same date` and `warning(1054): Revision date has already been used`
* There are some confusing line numbers, e.g., `line 123` and `128.3`
* The warning count seems to be wrong (and why is this summary line only sometimes included?)

**Comment by SlavomirMazurPantheon** [comment]
Hello,

this will probably be mainly due to the yangdump-pro tool output.
I am going to investigate whether we can format output in better way.
I will keep you informed in this thread.

Regards,
Slavomir Mazur

**Comment by SlavomirMazurPantheon** [comment]
Hello,

1. I was able to improve formatting of the output (in terms on newlines): https://github.com/YangCatalog/sdo_analysis/pull/120
2. Messages are duplicated because of (this is from official documentation):
```
All sub-modules that are included, and all modules that are imported, are also validated. This is done in the order the
import or include statements are encountered. Errors and warnings that occur in included submodules or imported modules
may be repeated, if it is used more than once within the requested set of files to validate.
```
3. `128.3` means line number 128 and column number 3 - this is output of the yangdump-pro tool.
4. I also checked warnings/errors count = lines like this: `*** 2 Errors, 0 Warnings`
If line like this is present it means that error/warning occured directly in the validated module. If it is not, the warning/error occurred in imported/included modules.

It is a question whether we do or do not want to display these warnings/errors from imported/included (sub)modules.

Regards,
Slavomir Mazur

**Comment by wlupton** [comment]
Thanks for the changes. I don't think I see them yet on the live page? I will leave to you any decisions about what else (if anything) to change.

Some follow-up comments:
- I get that `128.3` means line 128 column 3; I was commenting on whether the problem is on line 123 or line 128 (but I understand that this is an internal yangdump-pro matter)
- I don't think that that quoted text about error message duplication quite addresses what I mentioned: what I mentioned is two similar blocks of text within a _single_ message, although I guess this might be due to being reported at both the "including module" and "included module" levels (again, this is an internal yangdump-pro matter)
- Your `*** 2 Errors, 0 Warnings` explanation is helpful: so I guess that it's this line that determines whether or not the yangdump-pro run is deemed to have passed or failed

And a new comment:
- It doesn't look to be easy to use [BBFYANGPageCompilation.html](https://yangcatalog.org/private-page/BBFYANGPageCompilation.html) to find the compilation result for a given module, but you can get compilation status from (for example) <https://yangcatalog.org/yang-search/module_details/bbf-dot1q-cfm-l2-forwarding>. Would it be possible for the compilation status (here "passed-with-warnings") to be a link that accesses details of the compilation result, e.g., a link to the appropriate [BBFYANGPageCompilation.html](https://yangcatalog.org/private-page/BBFYANGPageCompilation.html) table row?

**Comment by SlavomirMazurPantheon** [comment]
Changes are visible here (old pages): https://yangcatalog.org/private/BBFYANGPageCompilation.html
but unfortunately not here: https://yangcatalog.org/private-page/BBFYANGPageCompilation.html - It seems that also some UI adjustments are necessary (I am trying to fix it now).

You are able to display individual compilation-result, for example for module [bbf-dot1q-cfm-l2-forwarding](https://yangcatalog.org/yang-search/module_details/bbf-dot1q-cfm-l2-forwarding) compilation-result can be found here: https://yangcatalog.org/results/bbf-dot1q-cfm-l2-forwarding@2022-03-01_bbf.html
This link is also visible at Module details page.

**Comment by SlavomirMazurPantheon** [comment]
These two `<br>` are also an internal yangdump-pro matter - it puts 2 newlines between messages.
Unfortunately, each validator has a slightly different output. 
However, I can simply replace two newlines with one newline (or one newline with two newlines) so outputs will not look so different.

**Comment by wlupton** [comment]
Thanks. Whatever you think is best.

**Comment by SlavomirMazurPantheon** [comment]
I placed double newlines everywhere, it will make some longer outputs much more clear.
**NOTE:** I will open new thread for the duplicated errors/warnings - now closing this issue.
