### ISSUE TITLE
Some IETF drafts not processed ?

### ISSUE THREAD

**Issue by evyncke** [YangCatalog/sdo_analysis#122]
https://datatracker.ietf.org/doc/html/draft-palmero-opsawg-dmlmo-03 has several YANG modules but I cannot find them on YC.O ?

Thanks for investigating

-éric
@xorrkaz

**Comment by richardzilincikPantheon** [comment]
There appears to be a closing curly bracket missing in `ietf-lmo@2022-03-01.yang`. With an added `}` on a line just before the `<CODE ENDS>`, xym extracts the module successfully.
