### ISSUE TITLE
IETFCiscoAuthorsYANGPageCompilation.html is being generated incorrectly

### ISSUE THREAD

**Issue by richardzilincikPantheon** [YangCatalog/sdo_analysis#200]
Most rows seem to be misformatted in some way, and contain module names instead of the intended content.
https://yangcatalog.org/private/IETFCiscoAuthorsYANGPageCompilation.html

**Comment by richardzilincikPantheon** [comment]
Possibly fixed by #202

**Comment by SlavomirMazurPantheon** [comment]
I re-run cronjob script and problem is fixed now.
