### ISSUE TITLE
Increase the Y axis scale at https://yangcatalog.org/private/figures/IETFYANGOutOfRFC.png

### ISSUE THREAD

**Issue by bclaise** [YangCatalog/sdo_analysis#5]
Hi,

80 is not enough.

Regards, B.

**Comment by miroslavKovacPantheon** [comment]
This was set staticly to 80. I changed to amount of modules plus 10 so we ll have dinamically changed y top limit. Please check https://yang.amsl.com/private/figures/IETFYANGOutOfRFC.png. 

thank you
