### ISSUE TITLE
Graphs bad behavior

### ISSUE THREAD

**Issue by bclaise** [YangCatalog/sdo_analysis#6]
Hi,

Please correct this weirdness in this graph
https://yangcatalog.org/private/figures/IETFYANGOutOfRFC.png
https://yangcatalog.org/private/figures/IETFYANGPageCompilation.png

Regards, Benoit

**Comment by miroslavKovacPantheon** [comment]
fixed https://yang.amsl.com/private/figures/IETFYANGPageCompilation.png

**Comment by bclaise** [comment]
Still need to fix https://yangcatalog.org/private/figures/IETFYANGOutOfRFC.png

**Comment by miroslavKovacPantheon** [comment]
please see the one in yang.amsl.com.. yangcatalog.org is outdated until the server transition is done.

thank you
Miroslav Kovac
