### ISSUE TITLE
Modify yangGeneric.py script to handle a directory tree

### ISSUE THREAD

**Issue by SlavomirMazurPantheon** [YangCatalog/sdo_analysis#65]
Script should be able to handle directory tree, which means it should process all the .yang module in all the sub-directories in root directory, which is passed as **rootdir** argument.

**Comment by miroslavKovacPantheon** [comment]
This might be just forgotten todo in the script. I think we are handling this correctly. Please check and if so remove the todo from script and will close this as invalid.

**Comment by SlavomirMazurPantheon** [comment]
Checked - done
